[profile.default]
src = '.'
out = 'out'
libs = ['lib']
remappings = ["/=src/","openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/","BoringSolidity/=lib/BoringSolidity/contracts/","ds-test/=lib/forge-std/lib/ds-test/src/","forge-std/=lib/forge-std/src/","solmate/=lib/solmate/src/","utils/=utils/","libraries/=src/libraries/","interfaces/=src/interfaces/","cauldrons/=src/cauldrons/","staking/=src/staking/","swappers/=src/swappers/","oracles/=src/oracles/","strategies/=src/strategies/","tokens/=src/tokens/","periphery/=src/periphery/","mixins/=src/mixins/","lenses/=src/lenses/","surl/=lib/surl/src/","solady/=lib/solady/src/","forge-deploy/=lib/forge-deploy/contracts/","ExcessivelySafeCall/=lib/ExcessivelySafeCall/src/","safe-contracts/=lib/safe-contracts/contracts/","fuzzlib/=lib/fuzzlib/src/"]
optimizer = true
optimizer_runs = 400
evm_version = 'paris'
solc_version = '0.8.20+commit.a1b79de6'